#!/bin/bash
export NETWORK_LOCATION="$(networksetup -getcurrentlocation)"
if [ "$NETWORK_LOCATION" = "BBC On Network" ]; then
  if [[ "$1" == "localhost" || "$1" == "127.0.0.1" ]]; then
    nc -X 5 $1 $2
  else
    nc -x "socks-gw.reith.bbc.co.uk:1085" -X 5 $1 $2
  fi
else
  nc -X 5 $1 $2
fi

